// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarShowController from "./calendar_show_controller"
application.register("calendar-show", CalendarShowController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationAutocompleteController from "./location_autocomplete_controller"
application.register("location-autocomplete", LocationAutocompleteController)

import MapController from "./map_controller"
application.register("map", MapController)

import ShareButtonController from "./share_button_controller"
application.register("share-button", ShareButtonController)

import ToggleMapController from "./toggle_map_controller"
application.register("toggle-map", ToggleMapController)
